# Docker Compose Simple para el proyecto PYMEs
# ==============================================
# 
# Versi贸n simplificada que solo ejecuta la aplicaci贸n principal

services:
  # Aplicaci贸n principal
  pymes-dashboard:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pymes_clustering_app_simple
    ports:
      - "8501:8501"
    volumes:
      # Montar c贸digo para desarrollo (hot reload)
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
